Mention SmallerC
balintkissdev/awesome-dos pull request #13
Opened 2023-01-27 00:33 UTC by jiffygist

Another awesome and easy to use compiler. It uses nasm as its inline assembly. Not very efficient, unfortunately.

2023-01-30 22:04 UTC, balintkissdev requested changes

2023-01-30 22:04 UTC, balintkissdev commented on readme.md
> +- [SmallerC](https://github.com/alexfru/SmallerC.git) - portable self-hosting C compiler capable of producing executables for a number of platforms, including real and protected mode DOS programs, by
CI doesn't let the new changes pass. The description needs to start with a capital letter like this:

```
Portable self-hosting C compiler capable of producing executables for a number of platforms, including real and protected mode DOS programs, by Alexei A. Frounze.
```

2023-01-31 13:47 UTC, gera2342 commented on readme.md
> +- [SmallerC](https://github.com/alexfru/SmallerC.git) - portable self-hosting C compiler capable of producing executables for a number of platforms, including real and protected mode DOS programs, by
Corrected.

2023-02-03 19:19 UTC, merged

2023-02-03 19:21 UTC, balintkissdev commented
Thanks @jiffygist for the contribution! ^^

There were some issues I was fighting with during additional CI linting, but I was not able to resolve them due to network accessibility of already existing web.archive.com links. Regardless of that I merged this PR.